# Generated by Django 6.0.6 on 2026-06-10 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtelierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('designer', 'Designer'), ('developer', 'Développeur'), ('both', 'Designer & Développeur')], default='designer', max_length=20)),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('skills', models.CharField(blank=True, max_length=500, verbose_name='Compétences')),
                ('avatar_url', models.URLField(blank=True, verbose_name='Avatar URL')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atelier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Atelier',
                'verbose_name_plural': 'Profils Atelier',
            },
        ),
        migrations.CreateModel(
            name='CodeRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du repo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('language', models.CharField(max_length=50, verbose_name='Langage')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('code_content', models.TextField(blank=True, verbose_name='Code source')),
                ('github_url', models.URLField(blank=True, verbose_name='Lien GitHub')),
                ('stars', models.IntegerField(default=0, verbose_name='Stars')),
                ('forks', models.IntegerField(default=0, verbose_name='Forks')),
                ('downloads', models.IntegerField(default=0, verbose_name='Téléchargements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='studio.atelierprofile')),
            ],
            options={
                'verbose_name': 'Repository de code',
                'verbose_name_plural': 'Repositories de code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('image_url', models.URLField(blank=True, verbose_name='Image URL')),
                ('figma_url', models.URLField(blank=True, verbose_name='Lien Figma')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('downloads', models.IntegerField(default=0, verbose_name='Téléchargements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='studio.atelierprofile')),
            ],
            options={
                'verbose_name': 'Projet portfolio',
                'verbose_name_plural': 'Projets portfolio',
                'ordering': ['-created_at'],
            },
        ),
    ]
