# Generated by Django 6.0.6 on 2026-06-10 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_atelierprofile_coderepository_portfolioproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphismeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('file_url', models.URLField(blank=True, verbose_name='URL du fichier')),
                ('preview_url', models.URLField(blank=True, verbose_name='URL de prévisualisation')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Type de fichier')),
                ('is_free', models.BooleanField(default=True, verbose_name='Gratuit')),
                ('downloads', models.IntegerField(default=0, verbose_name='Téléchargements')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix (TND)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphisme_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ressource graphique',
                'verbose_name_plural': 'Ressources graphiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
