# Generated by Django 6.0.6 on 2026-06-11 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_graphismeresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('matricule', models.CharField(blank=True, max_length=50, verbose_name='Matricule fiscal')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client ERP',
                'verbose_name_plural': 'Clients ERP',
            },
        ),
        migrations.CreateModel(
            name='ERPModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('auto-ecole', 'Auto-École'), ('sante', 'Santé / Clinique'), ('hotellerie', 'Hôtellerie / Tourisme'), ('commerce', 'Commerce / Retail'), ('juridique', 'Juridique'), ('comptabilite', 'Comptabilité'), ('rh-paie', 'RH & Paie')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Module ERP',
                'verbose_name_plural': 'Modules ERP',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ERPDemoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('value', models.CharField(max_length=200, verbose_name='Valeur')),
                ('extra', models.TextField(blank=True, verbose_name='Info supplémentaire')),
                ('status', models.CharField(default='active', max_length=50, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_records', to='studio.erpmodule')),
            ],
            options={
                'verbose_name': 'Enregistrement démo',
                'verbose_name_plural': 'Enregistrements démo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ERPSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='studio.erpclient')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='studio.erpmodule')),
            ],
            options={
                'verbose_name': 'Abonnement module',
                'verbose_name_plural': 'Abonnements modules',
                'unique_together': {('client', 'module')},
            },
        ),
    ]
