# Generated by Django 6.0.6 on 2026-06-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_candidat_categorie_chambre_clienthotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphismeresource',
            name='file',
            field=models.FileField(blank=True, upload_to='graphisme/files/', verbose_name='Fichier'),
        ),
        migrations.AddField(
            model_name='graphismeresource',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='graphisme/previews/', verbose_name='Image de prévisualisation'),
        ),
    ]
