# Generated by Django 6.0.6 on 2026-06-11 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_graphismeresource_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('categorie', models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat principal'), ('dessert', 'Dessert'), ('boisson', 'Boisson'), ('snack', 'Snack'), ('petit-dej', 'Petit-déjeuner')], default='plat', max_length=50, verbose_name='Catégorie')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix (TND)')),
                ('description', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article menu',
                'verbose_name_plural': 'Articles menu',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PatisserieRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Recette')),
                ('categorie', models.CharField(choices=[('patisserie', 'Pâtisserie'), ('boulangerie', 'Boulangerie'), ('chocolaterie', 'Chocolaterie'), ('confiserie', 'Confiserie'), ('glacier', 'Glacier'), ('traiteur', 'Traiteur')], default='patisserie', max_length=50)),
                ('ingredients', models.TextField(blank=True, verbose_name='Ingrédients')),
                ('instructions', models.TextField(blank=True)),
                ('cout_production', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Coût de production (TND)')),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix de vente (TND)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SoftCodeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du module')),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix (TND)')),
                ('disponible', models.BooleanField(default=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Module PixelSoftCode',
                'verbose_name_plural': 'Modules PixelSoftCode',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='StudioProject3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('architecture', 'Architecture'), ('interieur', 'Design intérieur'), ('exterieur', 'Design extérieur'), ('mecanique', 'Mécanique'), ('autre', 'Autre')], default='architecture', max_length=50)),
                ('fichier_url', models.URLField(blank=True, verbose_name='URL du fichier 3D')),
                ('image_url', models.URLField(blank=True, verbose_name='Image de prévisualisation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet 3D',
                'verbose_name_plural': 'Projets 3D',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='N° Table')),
                ('capacite', models.IntegerField(default=4)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée'), ('reservee', 'Réservée')], default='libre', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PatisserieProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('stock_actuel', models.IntegerField(default=0, verbose_name='Stock actuel')),
                ('stock_minimum', models.IntegerField(default=5, verbose_name='Stock minimum')),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix de vente (TND)')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='studio.patisserierecipe')),
            ],
            options={
                'verbose_name': 'Produit pâtisserie',
                'verbose_name_plural': 'Produits pâtisserie',
                'ordering': ['nom'],
            },
        ),
    ]
