# Generated by Django 6.0.6 on 2026-06-12 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_menuitem_patisserierecipe_softcodemodule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('categorie', models.CharField(choices=[('erp', 'GestiActiv ERP'), ('soft', 'PixelSoftCode'), ('restaurant', 'Restaurant'), ('patisserie', 'Pâtisserie'), ('studio', 'Inner Studio')], default='erp', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix (TND)')),
                ('duree_jours', models.IntegerField(default=365, verbose_name='Durée (jours)')),
                ('features', models.TextField(blank=True, help_text='Un par ligne')),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SouscriptionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email client')),
                ('client_nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('client_tel', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('status', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('expire', 'Expiré')], default='en_attente', max_length=20)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='studio.planabonnement')),
            ],
            options={
                'verbose_name': 'Souscription client',
                'verbose_name_plural': 'Souscriptions clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('especes', 'Espèces'), ('online', 'Paiement en ligne'), ('virement', 'Virement bancaire')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('refuse', 'Refusé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='ID Transaction')),
                ('notes', models.TextField(blank=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('souscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='studio.souscriptionclient')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='CleActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('est_utilisee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('souscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cles_activation', to='studio.souscriptionclient')),
            ],
            options={
                'verbose_name': "Clé d'activation",
                'verbose_name_plural': "Clés d'activation",
            },
        ),
    ]
