# Generated by Django 6.0.6 on 2026-06-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_planabonnement_souscriptionclient_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banque', models.CharField(choices=[('ATB', 'ATB — Arab Tunisian Bank'), ('Attijari', 'Attijari Bank'), ('Amen', 'Amen Bank'), ('BH', "Banque de l'Habitat"), ('BNA', 'BNA — Banque Nationale Agricole'), ('BIAT', 'BIAT — Banque Internationale Arabe de Tunisie'), ('BT', 'BT — Banque de Tunisie'), ('BTE', 'BTE — Banque Tunisie Emirates'), ('CFT', 'CFT — Banque CFT'), ('CGF', 'CGF Banque'), ('Poste', 'La Poste Tunisienne (CCP)'), ('STB', 'STB — Société Tunisienne de Banque'), ('TQB', 'TQB — Tunisian Qatari Bank'), ('UBCI', "UBCI — Union Bancaire pour le Commerce et l'Industrie"), ('UIB', 'UIB — Union Internationale de Banques'), ('Zitouna', 'Banque Zitouna'), ('Wifak', 'Wifak Bank'), ('autre', 'Autre')], default='BIAT', max_length=50, verbose_name='Banque')),
                ('agence', models.CharField(blank=True, max_length=100, verbose_name='Agence')),
                ('rib', models.CharField(max_length=24, verbose_name='RIB (24 chiffres)')),
                ('rip', models.CharField(blank=True, max_length=20, verbose_name='RIP')),
                ('swift', models.CharField(blank=True, max_length=11, verbose_name='Code SWIFT/BIC')),
                ('titulaire', models.CharField(max_length=200, verbose_name='Titulaire du compte')),
                ('est_defaut', models.BooleanField(default=False, verbose_name='Compte par défaut')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuration bancaire',
                'verbose_name_plural': 'Configurations bancaires',
                'ordering': ['-est_defaut', 'banque'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationPaiementEnLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(choices=[('expressee', 'Express eE (expressee.tn)'), ('d17', 'D17'), ('flouci', 'Flouci'), ('paymee', 'Paymee.tn'), ('konnect', 'Konnect'), ('manual', 'Manuel (instructions)')], default='manual', max_length=50, verbose_name='Fournisseur')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='Clé API')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='Secret API')),
                ('endpoint_url', models.URLField(blank=True, verbose_name="URL de l'API")),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions de paiement')),
                ('frais_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Frais (%)')),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration paiement en ligne',
                'verbose_name_plural': 'Configurations paiement en ligne',
            },
        ),
    ]
