# Generated by Django 6.0.6 on 2026-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_configurationbancaire_configurationpaiementenligne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_candidature', models.CharField(choices=[('worker', 'Worker (Employé)'), ('partner', 'Partner (Partenaire)'), ('freelance', 'Freelance / Prestataire'), ('stage', 'Stagiaire'), ('alternance', 'Alternance')], max_length=20, verbose_name='Type')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('poste', models.CharField(blank=True, max_length=200, verbose_name='Poste souhaité / Domaine')),
                ('cv', models.FileField(blank=True, upload_to='candidatures/cv/', verbose_name='CV')),
                ('message', models.TextField(blank=True, verbose_name='Message / Motivation')),
                ('linkedin', models.URLField(blank=True, verbose_name='Profil LinkedIn')),
                ('portfolio', models.URLField(blank=True, verbose_name='Portfolio / Site web')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('lu', 'Lu'), ('entretien', 'Entretien programmé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='nouveau', max_length=20)),
                ('notes_privees', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
