# Generated by Django 6.0.6 on 2026-06-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_candidature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeECommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('client_tel', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('client_adresse', models.TextField(verbose_name='Adresse de livraison')),
                ('client_ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('client_code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Instructions')),
                ('statut', models.CharField(choices=[('panier', 'Panier'), ('en_attente', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('preparation', 'En préparation'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='panier', max_length=20)),
                ('methode_paiement', models.CharField(choices=[('especes', 'Espèces (livraison)'), ('online', 'Paiement en ligne'), ('virement', 'Virement bancaire'), ('carte', 'Carte bancaire (livraison)')], default='online', max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total HT')),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Total TTC')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('id_transaction', models.CharField(blank=True, max_length=200, verbose_name='ID Transaction paiement')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commande e‑commerce',
                'verbose_name_plural': 'Commandes e‑commerce',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='CommandeECommerceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire TTC')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='studio.commandeecommerce')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_items', to='studio.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée (achat/approvisionnement)'), ('sortie', 'Sortie (vente/perte)'), ('ajustement', 'Ajustement inventaire'), ('retour', 'Retour fournisseur')], max_length=20, verbose_name='Type mouvement')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('stock_avant', models.IntegerField(default=0)),
                ('stock_apres', models.IntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Réf. bon/document')),
                ('notes', models.TextField(blank=True)),
                ('cree_par', models.CharField(blank=True, max_length=100)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='studio.produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
