# Generated by Django 6.0.6 on 2026-06-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_commandeecommerce_commandeecommerceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom client')),
                ('entreprise', models.CharField(blank=True, max_length=200, verbose_name='Entreprise / Projet')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Poste / Rôle')),
                ('contenu', models.TextField(verbose_name='Témoignage')),
                ('note', models.IntegerField(default=5, verbose_name='Note (1-5)')),
                ('photo', models.ImageField(blank=True, upload_to='temoignages/', verbose_name='Photo')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_at'],
            },
        ),
    ]
