# Generated by Django 6.0.7 on 2026-07-15 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0012_temoignage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PixMailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Nom d'utilisateur"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse email"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=200, verbose_name="Mot de passe"),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom d'affichage"
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, verbose_name="Avatar")),
                (
                    "storage_used_mb",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Stockage utilisé (Mo)",
                    ),
                ),
                (
                    "storage_limit_mb",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        max_digits=8,
                        verbose_name="Stockage max (Mo)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pixmail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte PixMail",
                "verbose_name_plural": "Comptes PixMail",
            },
        ),
        migrations.CreateModel(
            name="PixMailContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Entreprise"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="studio.pixmailaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact PixMail",
                "verbose_name_plural": "Contacts PixMail",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PixMailFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du dossier"),
                ),
                (
                    "icon",
                    models.CharField(default="📁", max_length=10, verbose_name="Icône"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1EB482", max_length=7, verbose_name="Couleur"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_folders",
                        to="studio.pixmailaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier PixMail",
                "verbose_name_plural": "Dossiers PixMail",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PixMailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(max_length=254, verbose_name="Expéditeur"),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Destinataire"),
                ),
                (
                    "cc",
                    models.EmailField(blank=True, max_length=254, verbose_name="CC"),
                ),
                (
                    "bcc",
                    models.EmailField(blank=True, max_length=254, verbose_name="CCI"),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="Objet")),
                ("body", models.TextField(verbose_name="Corps du message")),
                ("body_html", models.TextField(blank=True, verbose_name="Corps HTML")),
                (
                    "folder",
                    models.CharField(
                        choices=[
                            ("inbox", "Boîte de réception"),
                            ("sent", "Envoyés"),
                            ("draft", "Brouillons"),
                            ("spam", "Spam"),
                            ("trash", "Corbeille"),
                            ("archive", "Archives"),
                        ],
                        default="inbox",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "is_starred",
                    models.BooleanField(default=False, verbose_name="Favori"),
                ),
                ("has_attachments", models.BooleanField(default=False)),
                ("size_kb", models.IntegerField(default=0, verbose_name="Taille (Ko)")),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
                ("date_read", models.DateTimeField(blank=True, null=True)),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="studio.pixmailmessage",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to="studio.pixmailaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message PixMail",
                "verbose_name_plural": "Messages PixMail",
                "ordering": ["-date_sent"],
            },
        ),
        migrations.CreateModel(
            name="PixMailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Nom du fichier"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="pixmail/attachments/", verbose_name="Fichier"
                    ),
                ),
                ("size_kb", models.IntegerField(default=0, verbose_name="Taille (Ko)")),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Type MIME"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="studio.pixmailmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe PixMail",
                "verbose_name_plural": "Pièces jointes PixMail",
            },
        ),
        migrations.CreateModel(
            name="PixMailSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Signature")),
                (
                    "include_name",
                    models.BooleanField(default=True, verbose_name="Inclure le nom"),
                ),
                (
                    "include_email",
                    models.BooleanField(default=True, verbose_name="Inclure l'email"),
                ),
                (
                    "include_phone",
                    models.BooleanField(
                        default=False, verbose_name="Inclure le téléphone"
                    ),
                ),
                (
                    "include_company",
                    models.BooleanField(
                        default=True, verbose_name="Inclure l'entreprise"
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature",
                        to="studio.pixmailaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signature PixMail",
                "verbose_name_plural": "Signatures PixMail",
            },
        ),
    ]
