# Generated by Django 4.2.30 on 2026-07-18 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0014_conversation_encryptedmessage_post_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde (TND)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('type_operation', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('paiement', 'Paiement'), ('remboursement', 'Remboursement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (TND)')),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde avant')),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde après')),
                ('methode', models.CharField(choices=[('d17', 'D17'), ('flouci', 'Flouci'), ('konnect', 'Konnect'), ('wallet', 'Wallet'), ('carte', 'Carte bancaire'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], default='wallet', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('qr_data', models.TextField(blank=True, verbose_name='QR Code data')),
                ('payment_url', models.URLField(blank=True, verbose_name='Lien de paiement')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Nom client')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email client')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='studio.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
