# Generated by Django 4.2.30 on 2026-07-18 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0016_wallet_pixsoftwaredesign_1m'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=32, verbose_name='Secret TOTP')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='2FA activée')),
                ('backup_codes', models.TextField(blank=True, verbose_name='Codes de secours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twofactor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentification 2FA',
                'verbose_name_plural': 'Authentifications 2FA',
            },
        ),
    ]
