# Generated by Django 6.0.7 on 2026-07-19 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0018_referral"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("cin", "Carte d'identité nationale"),
                            ("passport", "Passeport"),
                            ("bank_account", "Relevé bancaire"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(max_length=50, verbose_name="Numéro du document"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nom complet"),
                ),
                (
                    "front_image",
                    models.ImageField(upload_to="kyc/front/", verbose_name="Recto"),
                ),
                (
                    "back_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="kyc/back/",
                        verbose_name="Verso",
                    ),
                ),
                (
                    "bank_rib",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="RIB bancaire"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="Note admin")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vérification KYC",
                "verbose_name_plural": "Vérifications KYC",
                "ordering": ["-created_at"],
            },
        ),
    ]
