# Generated by Django 6.0.7 on 2026-07-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0020_partner_balancetaxsafety"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="Photo de profil",
            ),
        ),
    ]
