# Generated by Django 5.2.17 on 2026-08-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0023_create_user_hajerghiloufi"),
    ]

    operations = [
        migrations.AddField(
            model_name="projetcontact",
            name="a_repondu",
            field=models.BooleanField(default=False, verbose_name="Réponse envoyée"),
        ),
        migrations.AddField(
            model_name="projetcontact",
            name="date_reponse",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de réponse"
            ),
        ),
    ]
