# Generated by Django 5.2.17 on 2026-09-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0024_contact_reply"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sujet",
                    models.CharField(max_length=200, verbose_name="Sujet de l'email"),
                ),
                ("contenu_html", models.TextField(verbose_name="Contenu HTML")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_envoi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "nb_destinataires",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de destinataires"
                    ),
                ),
                (
                    "envoye",
                    models.BooleanField(default=False, verbose_name="Campagne envoyée"),
                ),
            ],
            options={
                "verbose_name": "Campagne email",
                "verbose_name_plural": "Campagnes email",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "nom",
                    models.CharField(blank=True, max_length=150, verbose_name="Nom"),
                ),
                (
                    "token",
                    models.CharField(
                        default="b1a380025ee04e62a51c51d9923642ec",
                        max_length=40,
                        unique=True,
                        verbose_name="Token de désabonnement",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(default=True, verbose_name="Abonné actif"),
                ),
                (
                    "date_inscription",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonné newsletter",
                "verbose_name_plural": "Abonnés newsletter",
                "ordering": ["-date_inscription"],
            },
        ),
    ]
