version: '3.8'
services:
  mongodb:
    image: mongo:7
    container_name: pixsoftpay-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: pixsoftpay
    volumes:
      - pixsoftpay_data:/data/db

volumes:
  pixsoftpay_data:
