# Generated by Django 6.0.7 on 2026-07-20 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChainState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "État de la blockchain",
                "verbose_name_plural": "États de la blockchain",
            },
        ),
        migrations.CreateModel(
            name="CryptoTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tx_id",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("from_address", models.CharField(max_length=64)),
                ("to_address", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "fee",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("signature", models.TextField(blank=True, default="")),
                (
                    "public_key",
                    models.CharField(blank=True, default="", max_length=130),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("block_index", models.IntegerField(blank=True, null=True)),
                ("block_hash", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Transaction Crypto",
                "verbose_name_plural": "Transactions Crypto",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MiningStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_blocks", models.IntegerField(default=0)),
                ("total_mined", models.IntegerField(default=0)),
                ("difficulty", models.IntegerField(default=4)),
                ("hashrate", models.FloatField(default=0.0)),
                ("last_block_time", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stats Mining",
                "verbose_name_plural": "Stats Mining",
            },
        ),
        migrations.CreateModel(
            name="CryptoWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=64, unique=True)),
                ("public_key", models.CharField(max_length=130)),
                ("private_key_encrypted", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Crypto",
                "verbose_name_plural": "Wallets Crypto",
            },
        ),
    ]
