# Generated by Django 6.0.7 on 2026-07-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blockchain",
            "0002_premiumaccess_proposal_rewardlog_stake_dailylogin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotransaction",
            name="nonce",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cryptowallet",
            name="nonce",
            field=models.BigIntegerField(default=0),
        ),
    ]
